ERROR    root:test_httpRun.py:166 assert True == False
 +  where False = <DiaoApp.model.http_model.http_model object at 0x000001AB22AC3460>.assert_value
INFO     root:logDecoratorl.py:39 
>>===============================正在执行第11条用例======================================>>
测试标题: 未购买支付是否失败
请求方式: post
请求头:   {'accesstoken': '9be19dee5c4410546b6ca2ae7f0dcfac', 'timespan': '1660816346', 'TOKEN': '86AF2DC047BB1C1853DA37D4486B24DDB061DB08A2044CBA1B5F520F38081D10B4F625603662E02A2AEA7053B8BBA7211E7E2FAB668575B92FE968A4EA9F3227A6496BEF012D4236CE199BCF45E32D98'}
请求路径: http://110.80.137.11:8051/Payment/OrderPayment
传参方式： params
请求内容: {"orderid": "538726691959764131", "ordertype": "TAUCTION", "paytype": "1", "selfreturn": ""}
依赖测试用例: 暂无依赖用例数据
接口响应内容: {"success":true,"msg":"订单不存在","code":"","data":null}
接口响应时长: 0.111508 s
Http状态码: 200
断言方式：相等
期望结果：False
实际结果：[True]
>>==============================第11条用例执行完毕=======================================>>