ERROR    root:test_httpRun.py:152 assert 400 == 200
  +400
  -200
INFO     root:logDecoratorl.py:39 
>>===============================正在执行第4条用例======================================>>
测试标题: 账号、密码为空，登录失败
请求方式: post
请求头:   {'accesstoken': 'b8f6148a0d85fd42bba7caaa53963103', 'timespan': '1658998402'}
请求路径: http://110.80.137.11:8051/Users/Login_UserName
传参方式： params
请求内容: {
                "phone": "",
                "username":"",
                "password": "",
                "code": "",
                "invitecode": ""
            }
依赖测试用例: 暂无依赖用例数据
接口响应内容: {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-93e480838360eb9b298e6a9d043b1331-8615ca4e0746a6fe-00","errors":{"password":["The password field is required."],"username":["The username field is required."]}}
接口响应时长: 0.078088 s
Http状态码: 400
断言方式：相等
期望结果：False
实际结果：{'type': 'https://tools.ietf.org/html/rfc7231#section-6.5.1', 'title': 'One or more validation errors occurred.', 'status': 400, 'traceId': '00-93e480838360eb9b298e6a9d043b1331-8615ca4e0746a6fe-00', 'errors': {'password': ['The password field is required.'], 'username': ['The username field is required.']}}
>>==============================第4条用例执行完毕=======================================>>